### ISSUE TITLE
Feature Request: Suggestions for hearthstone management

### ISSUE THREAD

**Issue by Venkx** [MilleXIV/XIV_Databar#12]
You could consider making the hearthstones as a drop-down menu, that would save some space on the bar, especially because Legion adds another one.
Additionally, if it's possible, there could be more than one item to get to your hearth location (scroll of recall, dalaran ring) so if the hearthstone is on cooldown, it automatically uses another available item.

**Comment by MilleXIV** [comment]
Yup, was already thinking of making the "secondary" hearthstone (garrison/etc.) changeable via right-click. Similar to spec/lootspec. Since I'm working on the rewrite as top priority this might wait until after that. (Also, fun tip, shift-clicking this icon uses the Admiral's Compass.)

The "primary" hearthstone already checks for and uses multiple options. In order: Innkeeper's Daughter, Hearthstone, Astral Recall, Scroll of Recall (based on level). Are any of them not working for you?

**Comment by Venkx** [comment]
Well i've never tried it until now, just assumed something like that isn't implemented.
But yeah it works for me, thx!

**Comment by Mikeprod** [comment]
@Venkx if it works as mentioned above you can close this issue.
